version: "3"

services:
  nginx:
    container_name: otus_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:91:91"
    volumes:
      - ./symfony/:/var/www/symfony
    environment:
      - VIRTUAL_HOST=otus
    networks:
      - otus

  php:
    container_name: otus_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony
    networks:
      - otus

  postgres:
    container_name: otus_postgres
    image: postgres:11
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - otus
    volumes:
      - ./postgres/:/var/lib/postgresql/data

networks:
  otus:
    driver: bridge

volumes:
  otus:
    external: true