version: '3.1'
services:
  nginx:
    container_name: otus_nginx
    image: nginx:1.21.1-alpine
    restart: always
    ports:
      - '127.0.0.1:91:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    environment:
      - VIRTUAL_HOST=dev.otus
    networks:
      - otus

  php:
    container_name: otus
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    environment:
      APP_ENV: dev
    volumes:
      - ./:/var/www/html
    networks:
      - otus

  postgres:
    container_name: otus_postgres
    image: postgres:11
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - otus

networks:
  otus:
    driver: bridge
