<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCGqxLJk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCGqxLJk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCGqxLJk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCGqxLJk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCGqxLJk\App_KernelDevDebugContainer([
    'container.build_hash' => 'CGqxLJk',
    'container.build_id' => '51ab0480',
    'container.build_time' => 1612988140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCGqxLJk');
