security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            security: false
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator

    access_control:
#        - { path: ^/api/v1/user, roles: ROLE_ADMIN, methods: [ DELETE ] }
#        - { path: ^/api/v1/user/view, roles: ROLE_VIEW, methods: [ GET ] }

    role_hierarchy:
        ROLE_ADMIN: ROLE_VIEW

    access_decision_manager:
        strategy: consensus